<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SokobanExchangeFormatPreprocessor" nsURI="platform:/resource/SokobanExchangeFormatPreprocessor/model/SokobanExchangeFormatPreprocessor.ecore"
    nsPrefix="SokobanExchangeFormatPreprocessor">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="TODO: Add documentation for SokobanExchangeFormatPreprocessor. Hint: You may copy this element in the Ecore editor to add documentation to EClasses, EOperations, ..."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="NextLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="ecore:EClass ../../sokobanExchangeFormat/model/generated/SokobanExchangeFormat.ecore#//Entry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="ecore:EClass ../../sokobanExchangeFormat/model/generated/SokobanExchangeFormat.ecore#//Entry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedBoard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//NextLink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="board" eType="ecore:EClass ../../sokobanExchangeFormat/model/generated/SokobanExchangeFormat.ecore#//Board"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
