<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SokobanImportExport" nsURI="platform:/resource/SokobanImportExport/model/SokobanImportExport.ecore"
    nsPrefix="SokobanImportExport">
  <eClassifiers xsi:type="ecore:EClass" name="EntryToField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/sokobanExchangeFormat/model/generated/SokobanExchangeFormat.ecore#//Entry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/SokobanLanguage/model/SokobanLanguage.ecore#//Field"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoardToBoard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/sokobanExchangeFormat/model/generated/SokobanExchangeFormat.ecore#//Board"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/SokobanLanguage/model/SokobanLanguage.ecore#//Board"/>
  </eClassifiers>
</ecore:EPackage>
