<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Cheat1FacebookToInstagram" nsURI="platform:/resource/Cheat1FacebookToInstagram/model/Cheat1FacebookToInstagram.ecore"
    nsPrefix="Cheat1FacebookToInstagram">
  <eClassifiers xsi:type="ecore:EClass" name="NetworkToNetwork">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/FacebookLanguage/model/FacebookLanguage.ecore#//Network"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/InstagramLanguage/model/InstagramLanguage.ecore#//Network"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FbUserToInUser">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/FacebookLanguage/model/FacebookLanguage.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/InstagramLanguage/model/InstagramLanguage.ecore#//User"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FriendsFollowersBridgeRule__Marker"
      eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__fn" lowerBound="1"
        eType="ecore:EClass platform:/resource/FacebookLanguage/model/FacebookLanguage.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__fu" lowerBound="1"
        eType="ecore:EClass platform:/resource/FacebookLanguage/model/FacebookLanguage.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__in" lowerBound="1"
        eType="ecore:EClass platform:/resource/InstagramLanguage/model/InstagramLanguage.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__iu" lowerBound="1"
        eType="ecore:EClass platform:/resource/InstagramLanguage/model/InstagramLanguage.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__fn2in" lowerBound="1"
        eType="ecore:EClass platform:/resource/Cheat1FacebookToInstagram/model/Cheat1FacebookToInstagram.ecore#//FbUserToInUser"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__fu2iu" lowerBound="1"
        eType="ecore:EClass platform:/resource/Cheat1FacebookToInstagram/model/Cheat1FacebookToInstagram.ecore#//FbUserToInUser"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkToNetworkIslandRule__Marker"
      eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__fl" lowerBound="1"
        eType="ecore:EClass platform:/resource/FacebookLanguage/model/FacebookLanguage.ecore#//Network"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__il" lowerBound="1"
        eType="ecore:EClass platform:/resource/InstagramLanguage/model/InstagramLanguage.ecore#//Network"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__n2n" lowerBound="1"
        eType="ecore:EClass platform:/resource/Cheat1FacebookToInstagram/model/Cheat1FacebookToInstagram.ecore#//NetworkToNetwork"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserNetworkBridgeRule__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__f" lowerBound="1"
        eType="ecore:EClass platform:/resource/FacebookLanguage/model/FacebookLanguage.ecore#//Network"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__fu" lowerBound="1"
        eType="ecore:EClass platform:/resource/FacebookLanguage/model/FacebookLanguage.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__i" lowerBound="1"
        eType="ecore:EClass platform:/resource/InstagramLanguage/model/InstagramLanguage.ecore#//Network"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__iu" lowerBound="1"
        eType="ecore:EClass platform:/resource/InstagramLanguage/model/InstagramLanguage.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__f2i" lowerBound="1"
        eType="ecore:EClass platform:/resource/Cheat1FacebookToInstagram/model/Cheat1FacebookToInstagram.ecore#//NetworkToNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__fu2iu" lowerBound="1"
        eType="ecore:EClass platform:/resource/Cheat1FacebookToInstagram/model/Cheat1FacebookToInstagram.ecore#//FbUserToInUser"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserToUserIslandRule__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__flu" lowerBound="1"
        eType="ecore:EClass platform:/resource/FacebookLanguage/model/FacebookLanguage.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__ilu" lowerBound="1"
        eType="ecore:EClass platform:/resource/InstagramLanguage/model/InstagramLanguage.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__f2i" lowerBound="1"
        eType="ecore:EClass platform:/resource/Cheat1FacebookToInstagram/model/Cheat1FacebookToInstagram.ecore#//FbUserToInUser"/>
  </eClassifiers>
</ecore:EPackage>
