<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="UserToUI" nsURI="platform:/resource/UserToUI/model/UserToUI.ecore"
    nsPrefix="UserToUI">
  <eClassifiers xsi:type="ecore:EClass" name="ContextToApp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserToNavigation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Navigation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserToMinNav">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//MinimumNavigation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserToLessNav">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//LessInformedNav"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserToMoreNav">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//MoreInformedNav"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnviroToLay">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnviroToFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//TaskFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MUserToLayout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//MiddleAgeUser"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OUserToLayout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//OldAgeUser"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YUserToLayout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//YoungerUser"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserToLayout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlatformToNavigation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Navigation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnviroToNavigation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Navigation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlatformToLayout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlatformToTaskFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//TaskFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicRule__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__p" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__u" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Navigation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__t" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//TaskFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__e2l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//EnviroToLay"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__e2nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//EnviroToNavigation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__e2t" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//EnviroToFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__p2l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//PlatformToLayout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__p2nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//PlatformToNavigation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__p2t" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//PlatformToTaskFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__u2l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//UserToLayout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__u2nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//UserToNavigation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R10DayRule__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__sr" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//SunRise"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__t" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Time"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__cs" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//CustomColor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//EnviroToLay"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R11NightModeRule__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__sd" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//SunDawn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__t" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Time"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__cs" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//NightModeScheme"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//EnviroToLay"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R12VocalUI__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__ac" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__re" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//ReadEmail"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__t" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//TaskFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2t" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//EnviroToFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R13ImpairedVision__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__u" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__vi" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Reducedvision"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__fs" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//LargeSize"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__u2l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//UserToLayout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R14MiddleAgedUser__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__u" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//MiddleAgeUser"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__fs" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//MiddleSize"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__u2l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//MUserToLayout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R15OlderUser__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__u" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//OldAgeUser"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__fs" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//LargeSize"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__u2l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//OUserToLayout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R16YoungerUser__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__u" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//YoungerUser"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__fs" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//DefaultSize"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__u2l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//YUserToLayout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R17InexperiencedUser__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__ex" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Inexperienced"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__u" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__m" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//GridNav"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//MoreInformedNav"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__u2nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//UserToMoreNav"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R18ExperiencedUser__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__ex" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Experienced"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__u" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__m" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//DefaultNav"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Navigation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__u2nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//UserToNavigation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R19Smartphone__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__dt" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Smartphone"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__p" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__m" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//DefaultNav"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Navigation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__p2nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//PlatformToNavigation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R1BadMood__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__bm" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Badmood"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__u" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__b" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//FeedbackBar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__ce" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//ClickEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Navigation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__v" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Feedback"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__u2nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//UserToNavigation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R20Tablet__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__dt" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Tablet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__p" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__m" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//TabletNav"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Navigation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__p2nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//PlatformToNavigation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R21DrivingMode__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__ac" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__m" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//GridNav"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Navigation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//EnviroToNavigation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R22DeactivateDrivingMode__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__ac" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__m" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//DefaultNav"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Navigation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//EnviroToNavigation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R23LowBattery__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__bm" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//LowBatterymode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__p" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__cs" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//BlacknWhite"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__p2l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//PlatformToLayout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R24Charging__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__bm" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//NormalBatterymode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__p" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__cs" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//CustomColor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__p2l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//PlatformToLayout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R25WiFi__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__ct" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//ConnectionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__p" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__w" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Wifi"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__ad" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//AutoDownload"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__at" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Attachments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__ef" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//EmailForm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__h" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//HTML"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__re" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//ReadEmail"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__se" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//ShowEmail"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__ts" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//TaskFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__p2ts" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//PlatformToTaskFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R26FastMobileNetConnectionRule__Marker"
      eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__ce" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Cellular"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__cs3" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//ThreeG"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__cs4" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//FourG"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__ct" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//ConnectionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__p" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__ef" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//EmailForm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__h" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//HTML"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__se" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//ShowEmail"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__ts" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//TaskFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__p2ts" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//PlatformToTaskFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R27SlowMobileNetConnectionRule__Marker"
      eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__ce" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Cellular"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__cs" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//TwoG"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__ct" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//ConnectionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__p" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__ef" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//EmailForm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__se" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//ShowEmail"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__tf" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//TextForm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__ts" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//TaskFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__p2ts" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//PlatformToTaskFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R28DisableVocalUI__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__ac" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__ts" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//TaskFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2ts" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//EnviroToFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R2NeutralMood__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__nm" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Neutralmood"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__u" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Navigation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__u2nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//UserToNavigation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R3GoodMood__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__gm" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Goodmood"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__u" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__b" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//FeedbackBar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__ce" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//ClickEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Navigation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__v" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Inspiration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__u2nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//UserToNavigation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R4MinimalisticUserInterface__Marker"
      eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Experienced"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__u" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__minav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//MinimumNavigation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__u2minav"
        lowerBound="1" eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//UserToMinNav"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R5MinimizedNavigationInformation__Marker"
      eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__ex" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Intermediate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__u" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__lesnav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//LessInformedNav"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__u2nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//UserToLessNav"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R6DisplayExtraInfo__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__iex" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Inexperienced"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__u" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__mornav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//MoreInformedNav"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__CORR__u2nav" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//UserToMoreNav"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R7LowLight__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__lig" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Ambientlight"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__low" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//LowLight"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__cs" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//BlacknWhite"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//EnviroToLay"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R8NormalLight__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__lig" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Ambientlight"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__nor" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//NormalLight"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__cs" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//CustomColor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//EnviroToLay"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R9HighLight__Marker" eSuperTypes="platform:/plugin/org.emoflon.ibex.tgg.core.runtime/model/Runtime.ecore#//TGGRuleApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__c" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__e" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__SRC__high" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//HighLight"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__SRC__lig" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserEnviro/model/UserEnviro.ecore#//Ambientlight"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//App"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CREATE__TRG__cs" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//MonoChromatic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__TRG__l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UIAdaptation/model/UIAdaptation.ecore#//Layout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__c2a" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//ContextToApp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CONTEXT__CORR__e2l" lowerBound="1"
        eType="ecore:EClass platform:/resource/UserToUI/model/UserToUI.ecore#//EnviroToLay"/>
  </eClassifiers>
</ecore:EPackage>
